export const COUNTRY_SHOW_DATA_REQUEST = "COUNTRY_SHOW_DATA_REQUEST";
export const COUNTRY_SHOW_DATA_SUCCESS = "COUNTRY_SHOW_DATA_SUCCESS";
export const COUNTRY_SHOW_DATA_FAIL = "COUNTRY_SHOW_DATA_FAIL";



